- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    enabled: yes
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    gpgkey: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes

- name: enable required repositories
  rhsm_repository:
    name: rhel-7-server-rpms


- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: Install collectd and required plugins
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd

- name: Copy collectd config file
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: 0644

- name: start and enable collectd
  service:
    name: collectd
    state: started
    enabled: yes
