---

- hosts: load-drivers

  roles:
    - rhsm-registered

  tasks:

   - name: enable required repositories
     shell: subscription-manager repos --enable={{ item }}
     with_items:
       - rhel-7-server-rpms
       - rhel-7-server-extras-rpms
