- name: Install mariadb
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - MySQL-python 

- name: Enable mysql performance schema
  lineinfile:
    path: /etc/my.cnf.d/server.cnf
    state: present
    firstmatch: yes
    regexp: '\[mysqld\]'
    insertafter: '\[mysqld\]'
    line: 'performance_schema=ON'

- name: Install collectd-dbi
  yum:
    name: collectd-dbi
    state: present

- name: Start and enable mariadb-server
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: mariadb

- name: Add grafana user to the mariadb
  mysql_user:
    name: 'grafana'
    password: 'monitoring'
    priv: '*.*:ALL'
    state: present
    login_user: root

# TODO: disable all the metrics in the performance DB we're not using

- name: Open mariadb firewall ports
  firewalld:
    service: mysql
    permanent: true
    state: enabled
    




