---

- hosts: load-drivers

  roles:
    - rhsm-registered
    - monitoring

  vars:
    required_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms

  tasks:

   - name: enable required repositories
     rhsm_repository: name={{ required_repos | join(',') }}
     register: enabled_repos

   - name: Disable all repositories except required_repos
     rhsm_repository:
       name: "{{ enabled_repos.repositories |
        map(attribute='id') |
        difference(required_repos) |
        join(',' ) }}"
       state: disabled

   - name: install docker and ansible dependencies
     package: name={{ item }} state=present
     with_items:
       - docker
       - docker-python

   - name: start and enable docker
     service:
       name: docker
       state: started
       enabled: yes

   - name: pull down load driver containers
     docker_image: name={{ item }}
     with_items:
        - dmesser/ds2mysqldriver
        - dmesser/ds3webdriver

   - name: install python dependencies
     package: name={{ item }} state=present
     with_items:
       - MySQL-python

   - name: copy the benchmark script
     copy:
        src: files/run_bench.py
        dest: /root/
        owner: root
        group: root
        mode: 0755

   - name: create config files for the containers
     file: path=/root/dsmysqldriver state=directory
     #file: path=/root/ds3mysqldriver state=directory

- hosts: load1.poc4.maxta.com
  tasks:

     template:
         src: templates/DriverConfig.txt.j2
         dest: /root/ds2mysqldriver/DriverConfig.txt.{{ item.0 }}
         owner: root
         group: root
         mode: 0644
     #with_sequence:
         #start: 0 end: 253 stride: 4
     loop: "{{ range(0,50,1)|list|zip(range(0,150,3))|list }}"
