---

- hosts: load-drivers

  roles:
    - rhsm-registered
    - monitoring

  vars:
    required_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms

  tasks:

   - name: enable required repositories
     rhsm_repository: name={{ item }}
     with_items: "{{ required_repos }}"
     register: enabled_repos

   - name: Disable all repositories except required_repos
     rhsm_repository:
       name: "{{ item }}"
       state: disabled
     with_items: "{{ enabled_repos.results | last | attr(repositories) |
      map(attribute='id') |
      difference(required_repos) }}"

   - name: install docker and ansible dependencies
     package: name={{ item }} state=present
     with_items:
       - docker
       - docker-python

   - name: start and enable docker
     service:
       name: docker
       state: started
       enabled: yes

   - name: pull down load driver containers
     docker_image: name={{ item }}
     with_items:
        - dmesser/ds2mysqldriver
        - dmesser/ds3webdriver
